## Vectores y Valores Propios de una Matriz
#### Ashley Mercado Defort

El siguiente algoritmo implementa el proceso para hallar los valores y vectores propios de una matriz. Este algoritmo toma una matriz 𝑉 como entrada y retorna los valores y espacios propios de la matriz. 

In [1]:
import numpy as np

def calcular_autovalores_autovectores(matriz):
    # Asegurarse de que la matriz sea un array de NumPy
    matriz = np.array(matriz)
    
    # Calcular autovalores y autovectores
    autovalores, autovectores = np.linalg.eig(matriz)
    
    return autovalores, autovectores


matriz = np.array([[4, -2],
                    [1,  1]])
autovalores, autovectores = calcular_autovalores_autovectores(matriz)
print("Autovalores:", autovalores)
print("Autovectores:\n", autovectores)


Autovalores: [3. 2.]
Autovectores:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


## Proceso de Diagonalizacion

In [2]:
import numpy as np

def diagonalizar_matriz(matriz):
    matriz = np.array(matriz)
    
    # Calcular autovalores y autovectores
    autovalores, autovectores = np.linalg.eig(matriz)
    
    if np.linalg.matrix_rank(autovectores) == matriz.shape[0]:
        P = autovectores
        D = np.diag(autovalores)
        P_inv = np.linalg.inv(P)
        return P, D
    else:
        return None

matriz = np.array([[4, -2],
                    [1,  1]])
resultado = diagonalizar_matriz(matriz)
if resultado is not None:
    P, D = resultado
    print("Matriz de autovectores (P):\n", P)
    print("Matriz diagonal (D):\n", D)
else:
    print("La matriz no es diagonalizable.")


Matriz de autovectores (P):
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
Matriz diagonal (D):
 [[3. 0.]
 [0. 2.]]
