## Proceso de Ortogonalización de Gram-Schimdt
#### Ashley Mercado Defort

El siguiente algoritmo implementa el proceso de ortogonalización de Gram-Schmidt utilizando la biblioteca NumPy. Este algoritmo toma una matriz 𝑉 como entrada y produce una matriz ortogonalizada 𝑈 como salida. En resumen, se itera sobre los vectores de 𝑉 y se proyecta cada uno sobre los vectores ortogonales previamente encontrados en 𝑈, asegurando que cada nuevo vector sea ortogonal a los anteriores. Luego, se normalizan los vectores resultantes para asegurar que tengan norma 1. Finalmente, se retorna la matriz 𝑈 ortogonalizada y normalizada como resultado.

In [1]:
# Importar bibliotecas necesarias
import numpy 

# Definir función para realizar el proceso de ortogonalización de Gram-Schmidt
def GramSchmidt(V):
    tam = V.shape # Obtener dimensiones de la matriz V
    m = tam[0] # Número de filas
    n = tam[1] # Número de columnas
    U = numpy.zeros((m,n)) # Crear matriz U de ceros con las mismas dimensiones que V
    U[0] = V[0] # Asignar el primer vector de V a U

    for k in range(1,m):
        U[k] = V[k] # Asignar el vector k de V a U
        for j in range(k):
            U[k] = U[k] - (numpy.dot(U[j],V[k])/numpy.dot(U[j], U[j]))*(U[j]) # Realizar la ortogonalización de Gram-Schmidt

    for k in range(m):
        U[k] = U[k]/numpy.linalg.norm(U[k]) # Normalizar los vectores de U
    
    # Retornar la matriz U
    return U

# Ejemplo de uso de la función GramSchmidt
V= numpy.array([[1,1,0,1],[-1,2,0,0],[1,0,-1,2]]) # Definir matriz V
print(GramSchmidt(V)) # Imprimir matriz U

[[ 0.57735027  0.57735027  0.          0.57735027]
 [-0.6172134   0.77151675  0.         -0.15430335]
 [-0.39036003 -0.19518001 -0.68313005  0.58554004]]
